# Generated by Django 5.2.6 on 2025-09-10 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('em_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('em_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('em_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('em_blood_group', models.CharField(choices=[('O_POS', 'O+'), ('O_NEG', 'O-'), ('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-')], default='O+', max_length=10)),
                ('em_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('em_birthday', models.DateField(blank=True, null=True)),
                ('em_joining_date', models.DateField(blank=True, null=True)),
                ('em_contract_end', models.DateField(blank=True, null=True)),
                ('em_image', models.ImageField(blank=True, null=True, upload_to='images/employee/profile/')),
                ('em_nid', models.CharField(blank=True, max_length=64, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_reset_otp', models.BooleanField(default=False)),
                ('reset_password_token', models.UUIDField(blank=True, null=True)),
                ('reset_password_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='designation.designation')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
