# Generated by Django 5.2.6 on 2025-09-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='em_blood_group',
            field=models.CharField(blank=True, choices=[('O_POS', 'O+'), ('O_NEG', 'O-'), ('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='em_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
    ]
