# Generated by Django 5.2.6 on 2025-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_em_blood_group_alter_user_em_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='em_blood_group',
            field=models.CharField(choices=[('O_POS', 'O+'), ('O_NEG', 'O-'), ('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-')], default='B+', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='em_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='FEMALE', max_length=10),
        ),
    ]
