# Generated by Django 5.2.6 on 2025-09-10 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
